### ISSUE TITLE
How to create new sip user?

### ISSUE THREAD

**Issue by oney** [adhearsion/ruby_ami#30]
I am not sure whether this is a good place to ask questions about this repository.
I want to ask that how to create new sip user using RubyAMI. I read the document but it seems it doesn't mention. I know we can modify sip.conf and reload Asterisk to do it in terminal.
A new sip user like that in sip.conf

```
[1001]
type=friend
host=dynamic
secret=1001secret
context=demo
```

**Comment by benlangfeld** [comment]
As far as I know, it's not possible to add a peer to Asterisk via AMI. If you want to dynamically manage peers, look into Asterisk Realtime.

**Comment by bklang** [comment]
Actually, it is possible to create SIP peers via AMI.  In fact, almost 100% of Asterisk's configuration can be managed using Asterisk's generic [`UpdateConfig` AMI action](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_UpdateConfig).  The manager action might look something like this:

```
Action: UpdateConfig
ActionID: abc123
SrcFilename: sip.conf
DstFilename: sip.conf
Reload: true
Action-000000: NewCat
Cat-000000: 1001
Var-000000: type
Value-000000: friend
Var-000001: host
Value-000001: dynamic
Var-000002: secret
Value-000002: 1001secret
Var-000003: context
Value-000003: demo
```

**Comment by bklang** [comment]
Note that I'm not entirely clear whether or not you should increment the `00000*` numbers, or if they have to match for a single NewCat.  The Asterisk docs aren't entirely clear.

However, Adhearsion does do something similar to this when we boot, to ensure the transfer context is present. However it uses a different mechanism: https://github.com/adhearsion/punchblock/blob/develop/lib/punchblock/translator/asterisk.rb#L161
