### ISSUE TITLE
 undefined method `join' for Celluloid:Module (NoMethodError)

### ISSUE THREAD

**Issue by gravspeed** [adhearsion/ruby_ami#38]
i'm fairly new to ruby, debugging this eludes me....

i am using the first example code, ip user and password updated obviously. i know that the ami is listening because  i can log in with telnet. 

# ruby amitest.rb
I, [2016-05-24T11:51:37.502731 #12225]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
D, [2016-05-24T11:51:37.585088 #12225] DEBUG -- : Starting up...
D, [2016-05-24T11:51:37.719242 #12225] DEBUG -- : Finalizing stream
Received an event from Asterisk: #<RubyAMI::Stream::Disconnected:0x00000001fadd30>
amitest.rb:16:in `<main>': undefined method `join' for Celluloid:Module (NoMethodError)

# gem list | grep ruby_ami
ruby_ami (2.4.0)

# gem list | grep cell
celluloid (0.17.3)
celluloid-essentials (0.20.5)
celluloid-extras (0.20.5)
celluloid-fsm (0.20.5)
celluloid-io (0.17.3)
celluloid-pool (0.20.5)
celluloid-supervision (0.20.5)

**Comment by joshaidan** [comment]
I encountered the same problem. I suspect the API for celluloid has changed. You can try `Celluloid::Actor.join(stream)` which works, except for me it seems to stall at starting up.

Also, when I try the other supervise method:
```ruby
RubyAMI::Stream.supervise_as :ami_connection, '127.0.0.1', 5038, 'manager', 'password',
                              ->(e) { handle_event e },
                              Logger.new(STDOUT), 10
```
I get a different error: `undefined method 'services' for Celluloid:Module (NoMethodError)`

I noticed this project hasn't been updated in 3 years, so it might be worth looking into another AMI gem.

**Comment by benlangfeld** [comment]
> I noticed this project hasn't been updated in 3 years, so it might be worth looking into another AMI gem. Mis-read, updated in the last 7 months.

And that's because there's not really much to fix and no new features to be added. This is one of few projects which is mostly just "done".

This specific issue is because Celluloid is something of a moving target. [We don't yet support Celluloid 0.17](https://github.com/adhearsion/ruby_ami/commit/784610d802fb5ef36395f009387c3ddf27d537c0), but unfortunately that dep lockdown [isn't in a release yet](https://github.com/adhearsion/ruby_ami/compare/master...develop). I'll try to get that sorted out tomorrow.

**Comment by joshaidan** [comment]
Cool.

Well I cloned the source and build the gem from the developer branch and noticed this seems to already be fixed by:

```ruby
s.add_runtime_dependency %q<celluloid>, ["~> 0.16.0"]
```
But I noticed with Celluloid 0.16 you need to use `Celluloid::Actor.join(stream)` instead of `Celluloid.join(stream)`. I can submit a PR to update the README.md if you like.

**Comment by benlangfeld** [comment]
> I can submit a PR to update the README.md if you like.

Please do :)

**Comment by joshaidan** [comment]
I noticed when testing the `RubyAMI::Stream.supervise_as` example it seems to quit on my right away. But that would be a whole entirely different issue I would imagine.

**Comment by benlangfeld** [comment]
ruby_ami 3.0.0 just got released.
